<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (entry*, userMapping?, events?)>
<!ATTLIST config
    version CDATA #REQUIRED
>

<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry
    name CDATA #REQUIRED
>

<!ELEMENT userMapping (user*)>

<!ELEMENT user EMPTY>
<!ATTLIST user
    discord.user.id CDATA #REQUIRED
    trello.user.id CDATA #REQUIRED
>

<!ELEMENT events (event+)>

<!ELEMENT event (format, format, fields?)>
<!ATTLIST event
    name (CARD_CREATED | CARD_COMMENTED | CARD_MOVED | CARD_ADDED_LABEL | CARD_REMOVED_LABEL | CARD_DESCRIPTION_CHANGED | CARD_TITLE_CHANGED) #REQUIRED>

<!ELEMENT format ANY #PCDATA>
<!ATTLIST format
    key (title | body) #REQUIRED>

<!ELEMENT fields (field+)>

<!ELEMENT field (format, format)>