package tij.bot.trello2discord.common;

public enum MessageType {
    INVALID,
    CARD_CREATED,
    CARD_COMMENTED,
    CARD_MOVED,
    CARD_ADDED_LABEL,
    CARD_REMOVED_LABEL,
    CARD_DESCRIPTION_CHANGED,
    CARD_TITLE_CHANGED,
    CARD_MEMBER_ASSIGNED,
    CARD_MEMBER_UNASSIGNED;
}
