name: Commit
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        required: true
        default: patch
        description: What kind of commit?
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      prev_tag: ${{ steps.prev.outputs.prev_tag }}
      name: ${{ steps.release.outputs.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create patch bump commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          ./versioning.sh --bump=${{ inputs.bump }}
          git add pom.xml
          git commit -m "[ACTION] prepare next iteration $(./versioning.sh --string)"
          git push
